### PR TITLE
basic-text

### PR DESCRIPTION
**Pull request by pauleveritt**
Basic text for home page plus a new section for rendering using hyperpython.

### CODE REVIEW

**Comment by pauleveritt** [comment]
As a preview, [here is the rendered version](https://github.com/pauleveritt/htm.py/tree/basic-text/docs)

**Comment by rmorshea** [comment]
I'm not familiar with Hyperpython, but it may be worth looking at Nteract's [VDOM](https://github.com/nteract/vdom) as well for comparison. Admittedly, it looks like Hyperpython has great documentation, but VDOM has already been [integrated](https://github.com/jupyterlab/jupyterlab/tree/master/packages/vdom) into Jupyterlab, so it's got some solid support behind it as a "standard" of sorts. Maybe it just deserves another section in the docs.

**Comment by pauleveritt** [comment]
@rmorshea  Thanks for the comment. I might take a look. hyperpython has a number of dependencies which don't seem to install quite correctly. Didn't know jupyterlab shipped with VDOM.

Sure wish there was a dependency-free renderer.

**Comment by rmorshea** [comment]
If by "dependency-free" you mean something that's not tied to the Jupyter ecosystem, that's pretty much what I've made for IDOM. Haven't released it on NPM yet though:

https://github.com/rmorshea/idom/tree/master/src/js/packages/idom-layout

**Review by jviide — APPROVED** [review]
This is awesome! 👍

**Pull request merged**
